# Generated by Django 4.1.7 on 2023-02-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidstr', '0002_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='images',
            field=models.FileField(upload_to='uploaded/'),
        ),
    ]
