# Generated by Django 4.1.7 on 2023-02-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidstr', '0004_alter_posts_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='images',
            field=models.ImageField(blank=True, upload_to='uploaded/'),
        ),
    ]
