# Generated by Django 4.1.7 on 2023-02-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidstr', '0007_alter_posts_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='/static/images/default_profile_pic.png', upload_to='profile_pics/'),
        ),
    ]
