# Generated by Django 4.1.7 on 2023-02-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidstr', '0012_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='number_of_likes',
            field=models.FloatField(default=0),
        ),
    ]
