# Generated by Django 4.1.7 on 2023-02-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidstr', '0013_posts_number_of_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='number_of_likes',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
