# Generated by Django 4.1.7 on 2023-02-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidstr', '0016_remove_posts_number_of_likes_posts_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='like_status',
            field=models.BooleanField(default=False),
        ),
    ]
