# Generated by Django 4.1.7 on 2023-02-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidstr', '0019_alter_comments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='comments',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
