# Generated by Django 4.1.7 on 2023-02-27 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vidstr', '0020_posts_comments_delete_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='comments',
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(default='')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vidstr.posts')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vidstr.profile')),
            ],
        ),
    ]
