# Generated by Django 4.1.7 on 2023-02-27 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vidstr', '0023_alter_comments_profile_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='post_id',
            new_name='post',
        ),
    ]
