# Generated by Django 4.1.7 on 2023-02-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidstr', '0025_delete_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='comments',
            field=models.TextField(default=''),
        ),
    ]
