# Generated by Django 4.1.7 on 2023-02-27 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vidstr', '0026_posts_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='comments',
        ),
    ]
