# Generated by Django 4.1.7 on 2023-03-01 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vidstr', '0028_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment_body',
        ),
    ]
