# Generated by Django 4.1.7 on 2023-03-01 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vidstr', '0030_alter_posts_like_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_body',
            new_name='body',
        ),
    ]
